server {
  listen 80;
  client_max_body_size 520m;
  root /usr/share/nginx/html;
  location / {
    try_files $uri /index.html;
  }
  location /api/ {
    proxy_pass http://api:8001;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
  location /uploads/ {
    proxy_pass http://api:8001;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
