/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Products */
        get: operations["products_api_v1_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product */
        get: operations["product_api_v1_products__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Info */
        get: operations["session_info_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cart */
        get: operations["get_cart_api_v1_cart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Cart Item */
        put: operations["put_cart_item_api_v1_cart_items_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Cart Item */
        delete: operations["delete_cart_item_api_v1_cart_items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Notices
         * @description Active notices for the homepage banner, newest first.
         */
        get: operations["notices_api_v1_notices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pickup-days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pickup Days
         * @description Bookable pickup days for checkout: only future slots with seats left.
         */
        get: operations["pickup_days_api_v1_pickup_days_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storefront-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Storefront Config
         * @description Public feature flags the frontend needs before rendering checkout.
         *
         *     Single source of truth for whether online payment is offered right now;
         *     the frontend falls back to "disabled" if this call fails, so the pay-at-
         *     pickup-only path is always the safe default.
         */
        get: operations["storefront_config_api_v1_storefront_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checkout */
        post: operations["checkout_api_v1_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stripe/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe Webhook */
        post: operations["stripe_webhook_api_v1_stripe_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_v1_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/orders/{order_id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Demo Payment */
        post: operations["complete_demo_payment_api_v1_demo_orders__order_id__pay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/variants/{variant_id}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Stock
         * @description Legacy stock-only endpoint, kept working so existing callers don't break.
         *
         *     Superseded by PATCH /admin/variants/{variant_id}, which folds in price
         *     updates too; new integrations should use that route. This one now shares
         *     the same update_variant() logic instead of duplicating the stock checks.
         */
        patch: operations["update_stock_api_v1_admin_variants__variant_id__stock_patch"];
        trace?: never;
    };
    "/api/v1/admin/variants/{variant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Variant */
        patch: operations["patch_variant_api_v1_admin_variants__variant_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Products */
        get: operations["admin_products_api_v1_admin_products_get"];
        put?: never;
        /** Create Admin Product */
        post: operations["create_admin_product_api_v1_admin_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Admin Product */
        delete: operations["delete_admin_product_api_v1_admin_products__product_id__delete"];
        options?: never;
        head?: never;
        /** Patch Admin Product */
        patch: operations["patch_admin_product_api_v1_admin_products__product_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/products/{product_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Admin Product Image */
        post: operations["add_admin_product_image_api_v1_admin_products__product_id__images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{product_id}/images/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Admin Product Image */
        post: operations["upload_admin_product_image_api_v1_admin_products__product_id__images_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{product_id}/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Admin Product Image */
        delete: operations["delete_admin_product_image_api_v1_admin_products__product_id__images__image_id__delete"];
        options?: never;
        head?: never;
        /** Patch Admin Product Image */
        patch: operations["patch_admin_product_image_api_v1_admin_products__product_id__images__image_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/products/{product_id}/images/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder Admin Product Images */
        put: operations["reorder_admin_product_images_api_v1_admin_products__product_id__images_order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Orders */
        get: operations["admin_list_orders_api_v1_admin_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin Update Order */
        patch: operations["admin_update_order_api_v1_admin_orders__order_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/pickup-days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Pickup Days */
        get: operations["admin_list_pickup_days_api_v1_admin_pickup_days_get"];
        put?: never;
        /** Admin Create Pickup Day */
        post: operations["admin_create_pickup_day_api_v1_admin_pickup_days_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pickup-days/{pickup_day_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin Update Pickup Day */
        patch: operations["admin_update_pickup_day_api_v1_admin_pickup_days__pickup_day_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Notices */
        get: operations["admin_list_notices_api_v1_admin_notices_get"];
        put?: never;
        /** Admin Create Notice */
        post: operations["admin_create_notice_api_v1_admin_notices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/notices/{notice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Admin Delete Notice */
        delete: operations["admin_delete_notice_api_v1_admin_notices__notice_id__delete"];
        options?: never;
        head?: never;
        /** Admin Update Notice */
        patch: operations["admin_update_notice_api_v1_admin_notices__notice_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Audit Log */
        get: operations["admin_audit_log_api_v1_admin_audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddressIn */
        AddressIn: {
            /** Recipient Name */
            recipient_name: string;
            /** Line1 */
            line1: string;
            /** Line2 */
            line2?: string | null;
            /** City */
            city: string;
            /** Postal Code */
            postal_code: string;
            /** Country Code */
            country_code: string;
        };
        /** AdminCatalogPage */
        AdminCatalogPage: {
            /** Items */
            items: components["schemas"]["AdminCatalogProductOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * AdminCatalogProductOut
         * @description Like ProductOut, but includes inactive products/variants and their
         *     active flag -- the public ProductOut/VariantOut deliberately hide both, so
         *     the admin catalog view needs its own shape to manage a deactivated
         *     listing back to active.
         */
        AdminCatalogProductOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Active */
            active: boolean;
            /** Category */
            category: string | null;
            /** Category Slug */
            category_slug: string | null;
            /** Variants */
            variants: components["schemas"]["AdminVariantOut"][];
            /** Images */
            images: components["schemas"]["AdminImageOut"][];
        };
        /** AdminImageIn */
        AdminImageIn: {
            /** Url */
            url: string;
            /**
             * Alt Text
             * @default
             */
            alt_text: string;
            /** Caption */
            caption?: string | null;
            /**
             * Position
             * @default 0
             */
            position: number;
            /**
             * Media Type
             * @default image
             * @enum {string}
             */
            media_type: "image" | "video";
        };
        /** AdminImageOrderIn */
        AdminImageOrderIn: {
            /** Image Ids */
            image_ids: string[];
        };
        /** AdminImageOut */
        AdminImageOut: {
            /** Url */
            url: string;
            /** Alt Text */
            alt_text: string;
            /** Caption */
            caption?: string | null;
            /**
             * Media Type
             * @default image
             * @enum {string}
             */
            media_type: "image" | "video";
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** AdminImageUpdateIn */
        AdminImageUpdateIn: {
            /** Alt Text */
            alt_text?: string | null;
            /** Caption */
            caption?: string | null;
        };
        /** AdminNoticeIn */
        AdminNoticeIn: {
            /** Title */
            title: string;
            /** Body */
            body: string;
        };
        /** AdminNoticeOut */
        AdminNoticeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Active */
            active: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AdminNoticeUpdateIn */
        AdminNoticeUpdateIn: {
            /** Title */
            title?: string | null;
            /** Body */
            body?: string | null;
            /** Active */
            active?: boolean | null;
        };
        /** AdminOrderOut */
        AdminOrderOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Number */
            display_number: string;
            /** Status */
            status: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Subtotal Cents */
            subtotal_cents: number;
            /** Discount Cents */
            discount_cents: number;
            /** Shipping Cents */
            shipping_cents: number;
            /** Total Cents */
            total_cents: number;
            /** Currency */
            currency: string;
            /** Pickup At */
            pickup_at: string | null;
            /** Payment Method */
            payment_method: string;
            /** Items */
            items: components["schemas"]["OrderItemOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** User Id */
            user_id: string | null;
            /** Contact Handle */
            contact_handle?: string | null;
        };
        /** AdminOrderPage */
        AdminOrderPage: {
            /** Items */
            items: components["schemas"]["AdminOrderOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** AdminOrderStatusIn */
        AdminOrderStatusIn: {
            /** Status */
            status: string;
            /** Note */
            note?: string | null;
        };
        /** AdminPickupDayIn */
        AdminPickupDayIn: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Start Time
             * Format: time
             */
            start_time: string;
            /**
             * End Time
             * Format: time
             */
            end_time: string;
            /**
             * Slot Minutes
             * @default 15
             */
            slot_minutes: number;
            /**
             * Slot Capacity
             * @default 2
             */
            slot_capacity: number;
        };
        /** AdminPickupDayOut */
        AdminPickupDayOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Start Time
             * Format: time
             */
            start_time: string;
            /**
             * End Time
             * Format: time
             */
            end_time: string;
            /** Slot Minutes */
            slot_minutes: number;
            /** Slot Capacity */
            slot_capacity: number;
            /** Is Available */
            is_available: boolean;
        };
        /** AdminPickupDayUpdateIn */
        AdminPickupDayUpdateIn: {
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Slot Minutes */
            slot_minutes?: number | null;
            /** Slot Capacity */
            slot_capacity?: number | null;
            /** Is Available */
            is_available?: boolean | null;
        };
        /** AdminProductIn */
        AdminProductIn: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Category Slug */
            category_slug?: string | null;
            /** Images */
            images?: components["schemas"]["AdminImageIn"][];
            /** Variants */
            variants: components["schemas"]["AdminVariantCreateIn"][];
        };
        /** AdminProductUpdateIn */
        AdminProductUpdateIn: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Active */
            active?: boolean | null;
        };
        /** AdminStockIn */
        AdminStockIn: {
            /** Stock On Hand */
            stock_on_hand: number;
            /** Reason */
            reason: string;
        };
        /** AdminVariantCreateIn */
        AdminVariantCreateIn: {
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Weight Grams */
            weight_grams: number;
            /** Price Cents */
            price_cents: number;
            /**
             * Stock On Hand
             * @default 0
             */
            stock_on_hand: number;
        };
        /** AdminVariantOut */
        AdminVariantOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Weight Grams */
            weight_grams: number;
            /** Price Cents */
            price_cents: number;
            /** Available Stock */
            available_stock: number;
            /** Active */
            active: boolean;
            /** Stock On Hand */
            stock_on_hand: number;
            /** Stock Reserved */
            stock_reserved: number;
        };
        /** AdminVariantUpdateIn */
        AdminVariantUpdateIn: {
            /** Price Cents */
            price_cents?: number | null;
            /** Stock On Hand */
            stock_on_hand?: number | null;
            /** Active */
            active?: boolean | null;
            /** Reason */
            reason: string;
        };
        /** AuditLogOut */
        AuditLogOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Actor User Id
             * Format: uuid
             */
            actor_user_id: string;
            /** Actor Name */
            actor_name: string;
            /** Action */
            action: string;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AuditLogPage */
        AuditLogPage: {
            /** Items */
            items: components["schemas"]["AuditLogOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Body_upload_admin_product_image_api_v1_admin_products__product_id__images_upload_post */
        Body_upload_admin_product_image_api_v1_admin_products__product_id__images_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /**
             * Alt Text
             * @default
             */
            alt_text: string;
            /** Caption */
            caption?: string | null;
            /**
             * Position
             * @default 0
             */
            position: number;
        };
        /** CartItemIn */
        CartItemIn: {
            /**
             * Variant Id
             * Format: uuid
             */
            variant_id: string;
            /** Quantity */
            quantity: number;
            options?: components["schemas"]["DrinkOptionsIn"] | null;
        };
        /** CartItemOut */
        CartItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Variant Id
             * Format: uuid
             */
            variant_id: string;
            /** Product Slug */
            product_slug: string;
            /** Product Name */
            product_name: string;
            /** Variant Name */
            variant_name: string;
            /** Sku */
            sku: string;
            /** Quantity */
            quantity: number;
            /** Unit Price Cents */
            unit_price_cents: number;
            /** Line Total Cents */
            line_total_cents: number;
            /** Options */
            options?: {
                [key: string]: unknown;
            } | null;
        };
        /** CartOut */
        CartOut: {
            /** Items */
            items: components["schemas"]["CartItemOut"][];
            /** Subtotal Cents */
            subtotal_cents: number;
            /**
             * Currency
             * @default SEK
             */
            currency: string;
            /**
             * Needs Pickup
             * @default false
             */
            needs_pickup: boolean;
            /**
             * Needs Shipping
             * @default false
             */
            needs_shipping: boolean;
        };
        /** CheckoutIn */
        CheckoutIn: {
            /** Email */
            email?: string | null;
            shipping_address?: components["schemas"]["AddressIn"] | null;
            /** Pickup At */
            pickup_at?: string | null;
            /** Coupon Code */
            coupon_code?: string | null;
            /**
             * Payment Method
             * @default online
             * @enum {string}
             */
            payment_method: "online" | "pay_at_pickup";
            /** Contact Handle */
            contact_handle?: string | null;
        };
        /** CheckoutOut */
        CheckoutOut: {
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            /** Display Number */
            display_number: string;
            /** Checkout Url */
            checkout_url: string;
            /** Guest Lookup Token */
            guest_lookup_token: string | null;
            /** Reservation Expires At */
            reservation_expires_at?: string | null;
        };
        /**
         * DrinkOptionsIn
         * @description Per-line customisation for a drink. Unknown keys are rejected (422) rather
         *     than silently ignored, so a typo in a future field doesn't get dropped
         *     without notice.
         */
        DrinkOptionsIn: {
            /**
             * Matcha G
             * @default 4
             * @enum {integer}
             */
            matcha_g: 4 | 6;
            /**
             * Whisk
             * @default water
             * @enum {string}
             */
            whisk: "water" | "oat";
            /**
             * Base Milk
             * @default cow
             * @enum {string}
             */
            base_milk: "cow" | "oat";
            /**
             * Milk Ml
             * @default 130
             * @enum {integer}
             */
            milk_ml: 130 | 160;
            /**
             * Sugar G
             * @default 4
             * @enum {integer}
             */
            sugar_g: 2 | 4 | 6 | 8;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageOut */
        ImageOut: {
            /** Url */
            url: string;
            /** Alt Text */
            alt_text: string;
            /** Caption */
            caption?: string | null;
            /**
             * Media Type
             * @default image
             * @enum {string}
             */
            media_type: "image" | "video";
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** NoticeOut */
        NoticeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OrderItemOut */
        OrderItemOut: {
            /** Product Name */
            product_name: string;
            /** Variant Name */
            variant_name: string;
            /** Sku */
            sku: string;
            /** Unit Price Cents */
            unit_price_cents: number;
            /** Quantity */
            quantity: number;
            /** Options */
            options?: {
                [key: string]: unknown;
            } | null;
        };
        /** OrderOut */
        OrderOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Number */
            display_number: string;
            /** Status */
            status: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Subtotal Cents */
            subtotal_cents: number;
            /** Discount Cents */
            discount_cents: number;
            /** Shipping Cents */
            shipping_cents: number;
            /** Total Cents */
            total_cents: number;
            /** Currency */
            currency: string;
            /** Pickup At */
            pickup_at: string | null;
            /** Payment Method */
            payment_method: string;
            /** Items */
            items: components["schemas"]["OrderItemOut"][];
        };
        /** PickupDayPublicOut */
        PickupDayPublicOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Slots */
            slots: components["schemas"]["PickupSlotOut"][];
        };
        /** PickupSlotOut */
        PickupSlotOut: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Remaining */
            remaining: number;
        };
        /** ProductOut */
        ProductOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Category */
            category: string | null;
            /** Category Slug */
            category_slug: string | null;
            /** Variants */
            variants: components["schemas"]["VariantOut"][];
            /** Images */
            images: components["schemas"]["ImageOut"][];
        };
        /** ProductPage */
        ProductPage: {
            /** Items */
            items: components["schemas"]["ProductOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
        };
        /** SessionOut */
        SessionOut: {
            user: components["schemas"]["UserOut"];
            /** Csrf Token */
            csrf_token: string;
        };
        /** StorefrontConfigOut */
        StorefrontConfigOut: {
            /** Online Payments Enabled */
            online_payments_enabled: boolean;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Email Verified */
            email_verified: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VariantOut */
        VariantOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Weight Grams */
            weight_grams: number;
            /** Price Cents */
            price_cents: number;
            /** Available Stock */
            available_stock: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    products_api_v1_products_get: {
        parameters: {
            query?: {
                q?: string | null;
                category?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_api_v1_products__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                matcha_cart?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                matcha_cart?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_info_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cart_api_v1_cart_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                matcha_cart?: string | null;
                matcha_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_cart_item_api_v1_cart_items_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                matcha_cart?: string | null;
                matcha_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_cart_item_api_v1_cart_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: {
                matcha_cart?: string | null;
                matcha_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notices_api_v1_notices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoticeOut"][];
                };
            };
        };
    };
    pickup_days_api_v1_pickup_days_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickupDayPublicOut"][];
                };
            };
        };
    };
    storefront_config_api_v1_storefront_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorefrontConfigOut"];
                };
            };
        };
    };
    checkout_api_v1_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                matcha_cart?: string | null;
                matcha_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stripe_webhook_api_v1_stripe_webhook_post: {
        parameters: {
            query?: never;
            header?: {
                "Stripe-Signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_v1_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_demo_payment_api_v1_demo_orders__order_id__pay_post: {
        parameters: {
            query?: {
                lookup_token?: string | null;
            };
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stock_api_v1_admin_variants__variant_id__stock_patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                variant_id: string;
            };
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminStockIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_variant_api_v1_admin_variants__variant_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                variant_id: string;
            };
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminVariantUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_products_api_v1_admin_products_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCatalogPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_admin_product_api_v1_admin_products_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminProductIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_admin_product_api_v1_admin_products__product_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                product_id: string;
            };
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_admin_product_api_v1_admin_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                product_id: string;
            };
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminProductUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_admin_product_image_api_v1_admin_products__product_id__images_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                product_id: string;
            };
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminImageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCatalogProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_admin_product_image_api_v1_admin_products__product_id__images_upload_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                product_id: string;
            };
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_admin_product_image_api_v1_admin_products__product_id__images_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCatalogProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_admin_product_image_api_v1_admin_products__product_id__images__image_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                product_id: string;
                image_id: string;
            };
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCatalogProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_admin_product_image_api_v1_admin_products__product_id__images__image_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                product_id: string;
                image_id: string;
            };
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminImageUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCatalogProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_admin_product_images_api_v1_admin_products__product_id__images_order_put: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                product_id: string;
            };
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminImageOrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCatalogProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_orders_api_v1_admin_orders_get: {
        parameters: {
            query?: {
                status?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrderPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_order_api_v1_admin_orders__order_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                order_id: string;
            };
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminOrderStatusIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_pickup_days_api_v1_admin_pickup_days_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPickupDayOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_pickup_day_api_v1_admin_pickup_days_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminPickupDayIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPickupDayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_pickup_day_api_v1_admin_pickup_days__pickup_day_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                pickup_day_id: string;
            };
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminPickupDayUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPickupDayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_notices_api_v1_admin_notices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminNoticeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_notice_api_v1_admin_notices_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminNoticeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminNoticeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_notice_api_v1_admin_notices__notice_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                notice_id: string;
            };
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_notice_api_v1_admin_notices__notice_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                notice_id: string;
            };
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminNoticeUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminNoticeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_audit_log_api_v1_admin_audit_log_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                matcha_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
